# Module
# https://gohugo.io/hugo-modules/configuration/
# https://www.thenewdynamic.com/article/hugo-modules-everything-from-imports-to-create/
# ################################
mounts:
  - source: content/en
    target: content
    lang: en
  - source: content/fr
    target: content
    lang: fr
  - source: content/ja
    target: content
    lang: ja
  - source: uploads
    target: content/uploads
    lang: en
  - source: layouts
    target: layouts
  # Returning partials are core elements which should sit at the root of the project.
  - source: func
    target: layouts/partials/func
  - source: assets
    target: assets
  - source: _huge
    target: assets/_huge
  - source: uploads
    target: assets/uploads
imports:
  - path: github.com/theNewDynamic/huge
  - path: github.com/theNewDynamic/hugo-module-tnd-forms
  #- path: github.com/theNewDynamic/hugo-module-tnd-func