[build]
publish = "public"
command = "hugo --minify"

[build.environment]
  GO_VERSION = "1.14"
  NODE_VERSION = "15.4.0"
  HUGO_VERSION = "0.99.0"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify -e -D -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_ENV = "staging"

[context.branch-deploy]
command = "hugo --minify -e -b $DEPLOY_URL"
[context.branch-deploy.environment]
HUGO_ENV = "production"