fonts:
- family: AUDimat
  file: fonts/audimat-regular
  weight: 400
  style: normal
  display: swap
- family: Open Sans
  file: fonts/open-sans-v17-latin-300
  weight: 300
  style: normal
  display: swap
- family: Open Sans
  file: fonts/open-sans-v17-latin-300italic
  weight: 300
  style: italic
  display: swap
- family: Open Sans
  file: fonts/open-sans-v17-latin-regular
  weight: 400
  display: swap
- family: Open Sans
  file: fonts/open-sans-v17-latin-italic
  weight: 400
  style: italic
  display: swap
- family: Open Sans
  file: fonts/open-sans-v17-latin-600
  weight: 600
  display: swap
- family: Open Sans
  file: fonts/open-sans-v17-latin-600italic
  weight: 600
  style: italic
  display: swap
- family: Open Sans
  file: fonts/open-sans-v17-latin-700
  weight: 700
  style: normal
  display: swap
- family: Open Sans
  file: fonts/open-sans-v17-latin-700italic
  weight: 700
  style: italic
  display: swap